name: main

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '8 */10 10 * *'
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name : composer install
        shell: bash
        run : |
          php -v
          composer install  -q --no-ansi --no-interaction --no-progress
      - name : phpunit
        shell: bash
        run : |
          vendor/bin/phpunit
      - name : log
        shell: bash
        run : |
          date -I > last-tested.txt
      - name: push updated lists
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update tested date.
  run-composer-install:
    runs-on: ubuntu-latest
    steps:
      - name:  installation
        shell: bash
        run: |
          php -v
          composer require takuya/php-sysv-ipc-info
          cat <<'EOS' > sample.php
          <?php
          require_once 'vendor/autoload.php';
          $arr = \Takuya\SysV\sysvipc_info();
          $ret[] = isset($arr['shm']);
          $ret[] = isset($arr['msg']);
          $ret[] = isset($arr['sem']);
          $info = new \Takuya\SysV\IPCInfo;
          $info->show();

          var_dump( $ret == [true,true,true]);
          EOS
          cat sample.php
          php sample.php
      - name:  check command installed
        shell: bash
        run: |
          which vendor/bin/sysvipc
      - name:  run installed command
        shell: bash
        run: |
          vendor/bin/sysvipc
